class _BotCommands:
    def __init__(self):
        self.StartCommand = 'start'
        self.MirrorCommand = 'mirdl'
        self.UnzipMirrorCommand = 'unzipmirdl'
        self.TarMirrorCommand = 'tarmirdl'
        self.CancelMirror = 'canceldl'
        self.CancelAllCommand = 'cancelalldl'
        self.ListCommand = 'listdl'
        self.StatusCommand = 'statusdl'
        self.AuthorizedUsersCommand = 'usersdl'
        self.AuthorizeCommand = 'adlhdl'
        self.UnAuthorizeCommand = 'unadlhdl'
        self.AddSudoCommand = 'addsudodl'
        self.RmSudoCommand = 'rmsudodl'
        self.PingCommand = 'pingdl'
        self.RestartCommand = 'restartdl'
        self.StatsCommand = 'statsdl'
        self.HelpCommand = 'helpdl'
        self.LogCommand = 'logdl'
        self.SpeedCommand = 'speedtestdl'
        self.CloneCommand = 'clonedl'
        self.CountCommand = 'countdl'
        self.WatchCommand = 'watchdl'
        self.TarWatchCommand = 'tarwatch'
        self.DeleteCommand = 'deldl'
        self.UsageCommand = 'usagedl'
        self.MediaInfoCommand = 'mediainfodl'
        self.ConfigMenuCommand = 'configdl'
        self.ShellCommand = 'shelldl'
        self.UpdateCommand = 'updatedl'

BotCommands = _BotCommands()
