class _BotCommands:
    def __init__(self):
        self.StartCommand = 'start'
        self.MirrorCommand = 'mirbeta'
        self.UnzipMirrorCommand = 'unzipmirbeta'
        self.TarMirrorCommand = 'tarmirbeta'
        self.CancelMirror = 'cancelbeta'
        self.CancelAllCommand = 'cancelallbeta'
        self.ListCommand = 'listbeta'
        self.StatusCommand = 'statusbeta'
        self.AuthorizedUsersCommand = 'usersbeta'
        self.AuthorizeCommand = 'authbeta'
        self.UnAuthorizeCommand = 'unauthbeta'
        self.AddSudoCommand = 'addsudobeta'
        self.RmSudoCommand = 'rmsudobeta'
        self.PingCommand = 'pingbeta'
        self.RestartCommand = 'restartbeta'
        self.StatsCommand = 'statsbeta'
        self.HelpCommand = 'helpbeta'
        self.LogCommand = 'logbeta'
        self.SpeedCommand = 'speedtestbeta'
        self.CloneCommand = 'clonebeta'
        self.CountCommand = 'countbeta'
        self.WatchCommand = 'watchbeta'
        self.TarWatchCommand = 'tarwatch'
        self.DeleteCommand = 'delbeta'
        self.UsageCommand = 'usagebeta'
        self.MediaInfoCommand = 'mediainfobeta'
        self.ConfigMenuCommand = 'configbeta'
        self.ShellCommand = 'shellbeta'
        self.UpdateCommand = 'updatebeta'

BotCommands = _BotCommands()
